info:
  namespace: aquaculture

recipes:
  crafting_table:
    algae:
      enabled: true
      ingredients:
        A: aquaculture:algae
      result:
        amount: 1
        item: DRIED_KELP
      shapeless: true

    arrauturtle:
      enabled: true
      ingredients:
        A: aquaculture:arrauturtle
      result:
        amount: 1
        item: SCUTE
      shapeless: true

    boxturtle:
      enabled: true
      ingredients:
        A: aquaculture:boxturtle
      result:
        amount: 1
        item: SCUTE
      shapeless: true

    driftwood:
      enabled: true
      ingredients:
        A: aquaculture:driftwood
      result:
        amount: 4
        item: OAK_PLANKS

    fishbones:
      enabled: true
      ingredients:
        A: aquaculture:fishbones
      result:
        amount: 1
        item: BONE_MEAL

    jellyfish:
      enabled: true
      ingredients:
        A: aquaculture:jellyfish
      result:
        amount: 1
        item: SLIME_BALL
      shapeless: true

    starshellturtle:
      enabled: true
      ingredients:
        A: aquaculture:starshellturtle
      result:
        amount: 1
        item: SCUTE
      shapeless: true

    tincan:
      enabled: true
      ingredients:
        A: aquaculture:tincan
      result:
        amount: 1
        item: IRON_INGOT
      shapeless: true

    treasurechest:
      enabled: true
      ingredients:
        A: aquaculture:treasurechest
      result:
        amount: 1
        item: NETHERITE_BLOCK
      shapeless: true

    #
    # Recetas para el filete
    # 
    # Borra esto (o comentalo) si no tienes el add-on de
    # Pam's Harvestcraft, de lo contrario
    # estos cfrafteos no van a funcionar
    #
    # Descargalo de aquí: https://github.com/Casanaura/Pams-s-Harvestcraft-for-ItemsAdder
    #
    arapaima:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:arapaima
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    atlanticcod:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:atlanticcod
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    atlantichalibut:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:atlantichalibut
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    atlanticherring:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:atlanticherring
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    bayad:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:bayad
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    blackfish:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:blackfish
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    bluegill:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:bluegill
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    boulti:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:boulti
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    brownshrooma:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:brownshrooma
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    browntrout:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:browntrout
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    capitaine:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:capitaine
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    carp:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:carp
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    gar:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:gar
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    goldfish:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:goldfish
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    minnow:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:minnow
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    muskellunge:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:muskellunge
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    pacifichalibut:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:pacifichalibut
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    perch:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:perch
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    pinksalmon:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:pinksalmon
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    piranha:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:piranha
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    pollock:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:pollock
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    rainbowtrout:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:rainbowtrout
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    redgrouper:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:redgrouper
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    redshrooma:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:redshrooma
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    smallmouthbass:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:smallmouthbass
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    synodontis:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:synodontis
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    tambaqui:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:tambaqui
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    tuna:
      enabled: true
      ingredients:
        A: pamhc2foodcore:cuttingboarditem
        B: aquaculture:tuna
      result:
        amount: 1
        item: aquaculture:fishfilletraw
      shapeless: true
      return_items:
        decrement_durability:
          cuttingboard:
            item: pamhc2foodcore:cuttingboarditem
            amount: 1
    # Fin de recetas de filete
    # Borra (o comenta) hasta aquí

    # Neptunium
    neptuniumingot:
      enabled: true
      pattern:
      - AAA
      - AAA
      - AAA
      ingredients:
        A: aquaculture:neptuniumnugget
      result:
        amount: 1
        item: aquaculture:neptuniumingot
    neptuniumnugget:
      enabled: true
      ingredients:
        A: aquaculture:neptuniumingot
      result:
        amount: 9
        item: aquaculture:neptuniumnugget
      shapeless: true
    # Armadura
    neptuniumboots:
      enabled: true
      pattern:
      - AXA
      - AXA
      - XXX
      pattern_2:
      - XXX
      - AXA
      - AXA
      ingredients:
        A: aquaculture:neptuniumingot
      result:
        amount: 1
        item: aquaculture:neptuniumboots
    neptuniumchestplate:
      enabled: true
      pattern:
      - AXA
      - AAA
      - AAA
      ingredients:
        A: aquaculture:neptuniumingot
      result:
        amount: 1
        item: aquaculture:neptuniumchestplate
    neptuniumhelmet:
      enabled: true
      pattern:
      - AAA
      - AXA
      - XXX
      ingredients:
        A: aquaculture:neptuniumingot
      result:
        amount: 1
        item: aquaculture:neptuniumhelmet
    neptuniumleggings:
      enabled: true
      pattern:
      - AAA
      - AXA
      - AXA
      ingredients:
        A: aquaculture:neptuniumingot
      result:
        amount: 1
        item: aquaculture:neptuniumleggings
    # Herramientas
    neptuniumaxe:
      enabled: true
      pattern:
      - AAX
      - ABX
      - XBX
      pattern_2:
      - XAA
      - XBA
      - XBX
      ingredients:
        A: aquaculture:neptuniumingot
        B: STICK
      result:
        amount: 1
        item: aquaculture:neptuniumaxe
    neptuniumhoe:
      enabled: true
      pattern:
      - AAX
      - XBX
      - XBX
      pattern_2:
      - XAA
      - XBX
      - XBX
      ingredients:
        A: aquaculture:neptuniumingot
        B: STICK
      result:
        amount: 1
        item: aquaculture:neptuniumhoe
    neptuniumpickaxe:
      enabled: true
      pattern:
      - AAA
      - XBX
      - XBX
      ingredients:
        A: aquaculture:neptuniumingot
        B: STICK
      result:
        amount: 1
        item: aquaculture:neptuniumpickaxe
    neptuniumshovel:
      enabled: true
      pattern:
      - XAX
      - XBX
      - XBX
      ingredients:
        A: aquaculture:neptuniumingot
        B: STICK
      result:
        amount: 1
        item: aquaculture:neptuniumshovel
    neptuniumsword:
      enabled: true
      pattern:
      - XAX
      - XAX
      - XBX
      ingredients:
        A: aquaculture:neptuniumingot
        B: STICK
      result:
        amount: 1
        item: aquaculture:neptuniumsword
    neptuniumbow:
      enabled: true
      pattern:
      - XBC
      - BAA
      - XBC
      pattern_2:
      - CBX
      - AAB
      - CBX
      ingredients:
        A: aquaculture:neptuniumingot
        B: STICK
        C: STRING
      result:
        amount: 1
        item: aquaculture:neptuniumbow
    # Cañas y anzuelos
    neptuniumfishingrod:
      enabled: true
      pattern:
      - XXA
      - XAC
      - BXD
      pattern_2:
      - AXX
      - CAX
      - DXB
      ingredients:
        A: aquaculture:neptuniumingot
        B: STICK
        C: STRING
        D: aquaculture:netherstarhook
      result:
        amount: 1
        item: aquaculture:neptuniumfishingrod
    diamondfishingrod:
      enabled: true
      pattern:
      - XXA
      - XAC
      - BXD
      pattern_2:
      - AXX
      - CAX
      - DXB
      ingredients:
        A: DIAMOND
        B: STICK
        C: STRING
        D: aquaculture:diamondhook
      result:
        amount: 1
        item: aquaculture:diamondfishingrod
    diamondhook:
      enabled: true
      pattern:
      - XBX
      - BAB
      - XBX
      ingredients:
        A: aquaculture:ironhook
        B: DIAMOND
      result:
        amount: 1
        item: aquaculture:diamondhook
    goldfishingrod:
      enabled: true
      pattern:
      - XXA
      - XAC
      - BXD
      pattern_2:
      - AXX
      - CAX
      - DXB
      ingredients:
        A: GOLD_INGOT
        B: STICK
        C: STRING
        D: aquaculture:goldhook
      result:
        amount: 1
        item: aquaculture:goldfishingrod
    goldhook:
      enabled: true
      pattern:
      - XBX
      - BAB
      - XBX
      ingredients:
        A: aquaculture:ironhook
        B: GOLD_INGOT
      result:
        amount: 1
        item: aquaculture:goldhook
    ironfishingrod:
      enabled: true
      pattern:
      - XXA
      - XAC
      - BXD
      pattern_2:
      - AXX
      - CAX
      - DXB
      ingredients:
        A: IRON_INGOT
        B: STICK
        C: STRING
        D: aquaculture:ironhook
      result:
        amount: 1
        item: aquaculture:ironfishingrod
    ironhook:
      enabled: true
      pattern:
      - XXA
      - AXA
      - XAX
      pattern_2:
      - AXX
      - AXA
      - XAX
      ingredients:
        A: IRON_INGOT
      result:
        amount: 1
        item: aquaculture:ironhook
    netherstarhook:
      enabled: true
      ingredients:
        A: aquaculture:diamondhook
        B: DIAMOND
      result:
        amount: 1
        item: aquaculture:netherstarhook
      shapeless: true

  cooking:
    fishfilletcooked:
      ingredients:
        item: aquaculture:fishfilletraw
      machines:
      - FURNACE
      - SMOKER
      exp: 20
      cook_time: 200
      result:
        item: aquaculture:fishfilletcooked
        amount: 1