info:
  namespace: drugs

items:
  # Cocaína
  cocaineseed:
    display_name: display-name-cocaineseed
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: WHEAT_SEEDS
      textures:
      - item/drugs/cocaine_seed.png
    specific_properties:
      seed:
        crop_block: SWEET_BERRY_BUSH
        results:
          result_1:
            item: drugs:cocaineleaf
            min_amount: 1
            max_amount: 1
            chance: 5
  cocaineleaf:
    display_name: display-name-cocaineleaf
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/cocaine_leaf.png
  cocaine:
    display_name: display-name-cocaine
    durability:
      disappear_when_broken: true
      usages: 1
    events:
      interact.right:
        decrement_amount:
          amount: 1
        potion_effect:
          type: DARKNESS
          duration: 100
          amplifier: 1
        potion_effect_2:
          type: FAST_DIGGING
          duration: 18000
          amplifier: 3
        potion_effect_3:
          type: SPEED
          duration: 
          amplifier: 3
        potion_effect_4:
          type: DAMAGE_RESISTANCE
          duration: 18000
          amplifier: 3
        play_sound:
          delay: 0 
          name: minecraft:minecraft:entity.player.hurt.sweet.berry.bush
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: DRIED_KELP
      textures:
      - item/drugs/dried_cocaine.png
  cocainepackage:
    display_name: display-name-cocainepackage
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/dried_cocaine_package.png

  # Marihuana
  weedseed:
    display_name: display-name-weedseed
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: WHEAT_SEEDS
      textures:
      - item/drugs/hemp_seed.png
    specific_properties:
      seed:
        crop_block: SWEET_BERRY_BUSH
        results:
          result_1:
            item: drugs:weedleaf
            min_amount: 1
            max_amount: 1
            chance: 5
  weedleaf:
    display_name: display-name-weedleaf
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/hemp_leaf.png
  joint:
    display_name: display-name-joint
    durability:
      disappear_when_broken: true
      usages: 1
    events:
      interact.right:
        decrement_amount:
          amount: 1
        potion_effect:
          type: JUMP
          duration: 100
          amplifier: 3
        potion_effect_2:
          type: SLOW_FALLING
          duration: 200
          amplifier: 1
        potion_effect_3:
          type: REGENERATION
          duration: 18000
          amplifier: 3
        potion_effect_4:
          type: DARKNESS
          duration: 100
          amplifier: 1
        potion_effect_5:
          type: FIRE_RESISTANCE
          duration: 18000
          amplifier: 3
        play_sound:
          delay: 0 
          name: minecraft:entity.generic.extinguish.fire
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: DRIED_KELP
      textures:
      - item/drugs/joint.png
  weedpackage:
    display_name: display-name-weedpackage
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/leaf_package.png

  # Tabaco
  tobaccoleaf:
    display_name: display-name-tobaccoleaf
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/tobacco_leaf.png
  driedtobaccoleaf:
    display_name: display-name-driedtobaccoleaf
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/driedtobaccoleaf.png
  tobacco:
    display_name: display-name-tobacco
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/tobacco.png
  cigar:
    display_name: display-name-cigar
    durability:
      disappear_when_broken: true
      usages: 1
    events:
      interact.right:
        decrement_amount:
          amount: 1
        play_sound:
          delay: 0 
          name: minecraft:entity.generic.extinguish.fire
        potion_effect:
          type: SATURATION
          duration: 1200
          amplifier: 1
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: DRIED_KELP
      textures:
      - item/drugs/cigar.png
  cigarette:
    display_name: display-name-cigarette
    durability:
      disappear_when_broken: true
      usages: 1
    events:
      interact.right:
        decrement_amount:
          amount: 1
        play_sound:
          delay: 0 
          name: minecraft:entity.generic.extinguish.fire
        potion_effect:
          type: SATURATION
          duration: 600
          amplifier: 1
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: DRIED_KELP
      textures:
      - item/drugs/cigarette.png
  
  # Peyote
  peyote:
    display_name: display-name-peyote
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/peyote.png
  peyoteslice:
    display_name: display-name-peyoteslice
    durability:
      disappear_when_broken: true
      usages: 1
    events:
      interact.right:
        decrement_amount:
          amount: 1
        play_sound:
          delay: 0 
          name: minecraft:ambient.cave
        potion_effect:
          type: LEVITATION
          duration: 200
          amplifier: 1
        potion_effect_2:
          type: LUCK
          duration: 12000
          amplifier: 1
        potion_effect_3:
          type: SATURATION
          duration: 1200
          amplifier: 1
        potion_effect_4:
          type: HEAL
          duration: 300
          amplifier: 1
        potion_effect_5:
          type: SPEED
          duration: 12000
          amplifier: 2
        potion_effect_6:
          type: NIGHT_VISION
          duration: 12000
          amplifier: 1
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: DRIED_KELP
      textures:
      - item/drugs/peyoteslice.png
  
  # Hongos
  magicmushroom:
    display_name: display-name-magicmushroom
    durability:
      disappear_when_broken: true
      usages: 1
    events:
      interact.right:
        decrement_amount:
          amount: 1
        play_sound:
          delay: 0 
          name: minecraft:ambient.cave
        potion_effect:
          type: HEALTH_BOOST
          duration: 1200
          amplifier: 5
        potion_effect_2:
          type: FIRE_RESISTANCE
          duration: 12000
          amplifier: 1
        potion_effect_3:
          type: SLOW_FALLING
          duration: 12000
          amplifier: 1
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: DRIED_KELP
      textures:
      - item/drugs/magic_mushroom.png
  
  # LSD y LSA
  lsaseed:
    display_name: display-name-lsaseed
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: WHEAT_SEEDS
      textures:
      - item/drugs/lsa_seeds.png
    specific_properties:
      seed:
        crop_block: SWEET_BERRY_BUSH
        results:
          result_1:
            item: drugs:lsapowder
            min_amount: 1
            max_amount: 1
            chance: 5
  lsapowder:
    display_name: display-name-lsapowder
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/lsa.png
  pipewithlsa:
    display_name: display-name-pipewithlsa
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    durability:
      disappear_when_broken: true
      usages: 1
    events:
      interact.right:
        decrement_amount:
          amount: 1
        play_sound:
          delay: 0 
          name: minecraft:entity.player.hurt.sweet.berry.bush
        potion_effect:
          type: DARKNESS
          duration: 300
          amplifier: 1
        potion_effect_2:
          type: FAST_DIGGING
          duration: 1200
          amplifier: 1
        potion_effect_3:
          type: HEAL
          duration: 1200
          amplifier: 1
        potion_effect_4:
          type: INVISIBILITY
          duration: 1200
          amplifier: 1
    resource:
      generate: true
      material: DRIED_KELP
      textures:
      - item/drugs/pipewithdmt.png
  lsakohresidue:
    display_name: display-name-lsakohresidue
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/lsa_koh_residue.png
  lsdblotter:
    display_name: display-name-lsdblotter
    durability:
      disappear_when_broken: true
      usages: 1
    events:
      interact.right:
        decrement_amount:
          amount: 1
        play_sound:
          delay: 0 
          name: minecraft:minecraft:entity.player.hurt.sweet.berry.bush
        potion_effect:
          type: GLOWING
          duration: 1200
          amplifier: 1
        potion_effect_2:
          type: JUMP
          duration: 1200
          amplifier: 2
        potion_effect_3:
          type: ABSORPTION
          duration: 1200
          amplifier: 1
        potion_effect_4:
          type: WATER_BREATING
          duration: 1200
          amplifier: 1
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: DRIED_KELP
      textures:
      - item/drugs/lsd_blotter.png

  # Píldoras
  cbpill:
    display_name: display-name-cbpill
    durability:
      disappear_when_broken: true
      usages: 1
    events:
      interact.right:
        decrement_amount:
          amount: 1
        play_sound:
          delay: 0 
          name: minecraft:entity.player.hurt.sweet.berry.bush
        potion_effect:
          type: HEALTH_BOOST
          duration: 72000
          amplifier: 5
        potion_effect_2:
          type: ABSORPTION
          duration: 72000
          amplifier: 2
        potion_effect_3:
          type: SPEED
          duration: 72000
          amplifier: 3
        potion_effect_4:
          type: JUMP
          duration: 72000
          amplifier: 2
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: DRIED_KELP
      textures:
      - item/drugs/cb.png
  mdmapill:
    display_name: display-name-mdmapill
    durability:
      disappear_when_broken: true
      usages: 1
    events:
      interact.right:
        decrement_amount:
          amount: 1
        play_sound:
          delay: 0 
          name: minecraft:entity.player.hurt.sweet.berry.bush
        potion_effect:
          type: HEALTH_BOOST
          duration: 72000
          amplifier: 5
        potion_effect_2:
          type: ABSORPTION
          duration: 72000
          amplifier: 2
        potion_effect_3:
          type: SPEED
          duration: 72000
          amplifier: 3
        potion_effect_4:
          type: JUMP
          duration: 72000
          amplifier: 2
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: DRIED_KELP
      textures:
      - item/drugs/mdma_pill.png

  # Objetos Misceláneos
  emptypipe:
    display_name: display-name-emptypipe
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/pipe.png
  filter:
    display_name: display-name-filter
    lore:
    - '&f'
    - '&8Sustancias Estupefacientes'
    resource:
      generate: true
      material: PAPER
      textures:
      - item/drugs/filter.png